# Generated by Django 5.1.2 on 2024-10-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.TextField(max_length=100)),
                ('receipe_description', models.TextField(max_length=200)),
            ],
        ),
    ]
