# Generated by Django 5.1.2 on 2024-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homie', '0002_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
