# Generated by Django 5.1.2 on 2024-10-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homie', '0003_music_music_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_image',
            field=models.ImageField(null=True, upload_to='receipet'),
        ),
    ]
