# Generated by Django 5.1.2 on 2024-10-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homie', '0004_alter_music_music_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_image',
            field=models.ImageField(upload_to='receipet'),
        ),
    ]
